const STATIC_CONTENT_DIR_PATH = "src/content";
const FAQS_PAGE_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/faqs-page/index.json`;
const TERMS_PAGE_FILE_PATH = `${STATIC_CONTENT_DIR_PATH}/terms-page/index.json`;

exports.STATIC_CONTENT_DIR_PATH = STATIC_CONTENT_DIR_PATH;
exports.FAQS_PAGE_FILE_PATH = FAQS_PAGE_FILE_PATH;
exports.TERMS_PAGE_FILE_PATH = TERMS_PAGE_FILE_PATH;